package com.chendezhi.baidu.tieba.capture.hibernate;

// Generated 2014-6-14 2:03:37 by Hibernate Tools 3.4.0.CR1

/**
 * BaiduTiebaContentId generated by hbm2java
 */
public class BaiduTiebaContentId implements java.io.Serializable {

	private long titleId;
	private long floor;
	private int imgIdx;

	public BaiduTiebaContentId() {
	}

	public BaiduTiebaContentId(long titleId, long floor, int imgIdx) {
		this.titleId = titleId;
		this.floor = floor;
		this.imgIdx = imgIdx;
	}

	public long getTitleId() {
		return this.titleId;
	}

	public void setTitleId(long titleId) {
		this.titleId = titleId;
	}

	public long getFloor() {
		return this.floor;
	}

	public void setFloor(long floor) {
		this.floor = floor;
	}

	public int getImgIdx() {
		return this.imgIdx;
	}

	public void setImgIdx(int imgIdx) {
		this.imgIdx = imgIdx;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BaiduTiebaContentId))
			return false;
		BaiduTiebaContentId castOther = (BaiduTiebaContentId) other;

		return (this.getTitleId() == castOther.getTitleId())
				&& (this.getFloor() == castOther.getFloor())
				&& (this.getImgIdx() == castOther.getImgIdx());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getTitleId();
		result = 37 * result + (int) this.getFloor();
		result = 37 * result + this.getImgIdx();
		return result;
	}

}
