package com.chendezhi.baidu.tieba.capture.hibernate;

// Generated 2014-6-14 2:03:37 by Hibernate Tools 3.4.0.CR1

/**
 * BaiduTiebaContentTask generated by hbm2java
 */
public class BaiduTiebaContentTask implements java.io.Serializable {

	private long tiebaId;
	private int page;
	private long floor;

	public BaiduTiebaContentTask() {
	}

	public BaiduTiebaContentTask(long tiebaId, int page, long floor) {
		this.tiebaId = tiebaId;
		this.page = page;
		this.floor = floor;
	}

	public long getTiebaId() {
		return this.tiebaId;
	}

	public void setTiebaId(long tiebaId) {
		this.tiebaId = tiebaId;
	}

	public int getPage() {
		return this.page;
	}

	public void setPage(int page) {
		this.page = page;
	}

	public long getFloor() {
		return this.floor;
	}

	public void setFloor(long floor) {
		this.floor = floor;
	}

}
