package com.chendezhi.baidu.tieba.capture.hibernate;

// Generated 2014-6-14 2:03:37 by Hibernate Tools 3.4.0.CR1

/**
 * BaiduTiebaTitle generated by hbm2java
 */
public class BaiduTiebaTitle implements java.io.Serializable {

	private long id;
	private String tiebaName;
	private String title;
	private String authorName;
	private long replyNum;
	private Integer isGood;
	private Integer isTop;
	private boolean isNew;

	public BaiduTiebaTitle() {
	}

	public BaiduTiebaTitle(long id, String tiebaName, long replyNum,
			boolean isNew) {
		this.id = id;
		this.tiebaName = tiebaName;
		this.replyNum = replyNum;
		this.isNew = isNew;
	}

	public BaiduTiebaTitle(long id, String tiebaName, String title,
			String authorName, long replyNum, Integer isGood, Integer isTop,
			boolean isNew) {
		this.id = id;
		this.tiebaName = tiebaName;
		this.title = title;
		this.authorName = authorName;
		this.replyNum = replyNum;
		this.isGood = isGood;
		this.isTop = isTop;
		this.isNew = isNew;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTiebaName() {
		return this.tiebaName;
	}

	public void setTiebaName(String tiebaName) {
		this.tiebaName = tiebaName;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthorName() {
		return this.authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	public long getReplyNum() {
		return this.replyNum;
	}

	public void setReplyNum(long replyNum) {
		this.replyNum = replyNum;
	}

	public Integer getIsGood() {
		return this.isGood;
	}

	public void setIsGood(Integer isGood) {
		this.isGood = isGood;
	}

	public Integer getIsTop() {
		return this.isTop;
	}

	public void setIsTop(Integer isTop) {
		this.isTop = isTop;
	}

	public boolean isIsNew() {
		return this.isNew;
	}

	public void setIsNew(boolean isNew) {
		this.isNew = isNew;
	}

}
