package com.chendezhi.baidu.tieba.capture.hibernate;

// Generated 2014-6-11 14:21:00 by Hibernate Tools 3.4.0.CR1

/**
 * BaiduTiebaContentTaskId generated by hbm2java
 */
public class BaiduTiebaContentTaskId implements java.io.Serializable {

	private Long tiebaId;
	private Long page;
	private Long floor;

	public BaiduTiebaContentTaskId() {
	}

	public BaiduTiebaContentTaskId(Long tiebaId, Long page, Long floor) {
		this.tiebaId = tiebaId;
		this.page = page;
		this.floor = floor;
	}

	public Long getTiebaId() {
		return this.tiebaId;
	}

	public void setTiebaId(Long tiebaId) {
		this.tiebaId = tiebaId;
	}

	public Long getPage() {
		return this.page;
	}

	public void setPage(Long page) {
		this.page = page;
	}

	public Long getFloor() {
		return this.floor;
	}

	public void setFloor(Long floor) {
		this.floor = floor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BaiduTiebaContentTaskId))
			return false;
		BaiduTiebaContentTaskId castOther = (BaiduTiebaContentTaskId) other;

		return ((this.getTiebaId() == castOther.getTiebaId()) || (this
				.getTiebaId() != null && castOther.getTiebaId() != null && this
				.getTiebaId().equals(castOther.getTiebaId())))
				&& ((this.getPage() == castOther.getPage()) || (this.getPage() != null
						&& castOther.getPage() != null && this.getPage()
						.equals(castOther.getPage())))
				&& ((this.getFloor() == castOther.getFloor()) || (this
						.getFloor() != null && castOther.getFloor() != null && this
						.getFloor().equals(castOther.getFloor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTiebaId() == null ? 0 : this.getTiebaId().hashCode());
		result = 37 * result
				+ (getPage() == null ? 0 : this.getPage().hashCode());
		result = 37 * result
				+ (getFloor() == null ? 0 : this.getFloor().hashCode());
		return result;
	}

}
