package com.chendezhi.baidu.tieba.capture.hibernate;

// Generated 2014-6-14 2:03:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserToken generated by hbm2java
 */
public class UserToken implements java.io.Serializable {

	private long uid;
	private String accessToken;
	private long expiresIn;
	private Date authorizeAt;

	public UserToken() {
	}

	public UserToken(long uid, long expiresIn, Date authorizeAt) {
		this.uid = uid;
		this.expiresIn = expiresIn;
		this.authorizeAt = authorizeAt;
	}

	public UserToken(long uid, String accessToken, long expiresIn,
			Date authorizeAt) {
		this.uid = uid;
		this.accessToken = accessToken;
		this.expiresIn = expiresIn;
		this.authorizeAt = authorizeAt;
	}

	public long getUid() {
		return this.uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	public long getExpiresIn() {
		return this.expiresIn;
	}

	public void setExpiresIn(long expiresIn) {
		this.expiresIn = expiresIn;
	}

	public Date getAuthorizeAt() {
		return this.authorizeAt;
	}

	public void setAuthorizeAt(Date authorizeAt) {
		this.authorizeAt = authorizeAt;
	}

}
