package com.chendezhi.baidu.tieba.capture.hibernate;

// Generated 2014-6-14 2:03:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserSina generated by hbm2java
 */
public class UserSina implements java.io.Serializable {

	private long id;
	private String name;
	private Short provinceId;
	private Short cityId;
	private String location;
	private String description;
	private String url;
	private String profileImageUrl;
	private String domain;
	private String gender;
	private long followersCount;
	private long friendsCount;
	private long biFollowersCount;
	private long statusesCount;
	private Long favouritesCount;
	private Date activeAt;
	private Boolean verified;
	private Short verifiedType;
	private String verifiedReason;
	private String email;
	private String realName;
	private String birthday;
	private Byte birthdayVisible;
	private Integer credentialsNum;
	private Integer credentialsType;
	private String msn;
	private String qq;
	private String tags;
	private Date regTime;
	private Date refreshTime;

	public UserSina() {
	}

	public UserSina(long id, String name, String gender, long followersCount,
			long friendsCount, long biFollowersCount, long statusesCount,
			Date refreshTime) {
		this.id = id;
		this.name = name;
		this.gender = gender;
		this.followersCount = followersCount;
		this.friendsCount = friendsCount;
		this.biFollowersCount = biFollowersCount;
		this.statusesCount = statusesCount;
		this.refreshTime = refreshTime;
	}

	public UserSina(long id, String name, Short provinceId, Short cityId,
			String location, String description, String url,
			String profileImageUrl, String domain, String gender,
			long followersCount, long friendsCount, long biFollowersCount,
			long statusesCount, Long favouritesCount, Date activeAt,
			Boolean verified, Short verifiedType, String verifiedReason,
			String email, String realName, String birthday,
			Byte birthdayVisible, Integer credentialsNum,
			Integer credentialsType, String msn, String qq, String tags,
			Date regTime, Date refreshTime) {
		this.id = id;
		this.name = name;
		this.provinceId = provinceId;
		this.cityId = cityId;
		this.location = location;
		this.description = description;
		this.url = url;
		this.profileImageUrl = profileImageUrl;
		this.domain = domain;
		this.gender = gender;
		this.followersCount = followersCount;
		this.friendsCount = friendsCount;
		this.biFollowersCount = biFollowersCount;
		this.statusesCount = statusesCount;
		this.favouritesCount = favouritesCount;
		this.activeAt = activeAt;
		this.verified = verified;
		this.verifiedType = verifiedType;
		this.verifiedReason = verifiedReason;
		this.email = email;
		this.realName = realName;
		this.birthday = birthday;
		this.birthdayVisible = birthdayVisible;
		this.credentialsNum = credentialsNum;
		this.credentialsType = credentialsType;
		this.msn = msn;
		this.qq = qq;
		this.tags = tags;
		this.regTime = regTime;
		this.refreshTime = refreshTime;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Short getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Short provinceId) {
		this.provinceId = provinceId;
	}

	public Short getCityId() {
		return this.cityId;
	}

	public void setCityId(Short cityId) {
		this.cityId = cityId;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getProfileImageUrl() {
		return this.profileImageUrl;
	}

	public void setProfileImageUrl(String profileImageUrl) {
		this.profileImageUrl = profileImageUrl;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public long getFollowersCount() {
		return this.followersCount;
	}

	public void setFollowersCount(long followersCount) {
		this.followersCount = followersCount;
	}

	public long getFriendsCount() {
		return this.friendsCount;
	}

	public void setFriendsCount(long friendsCount) {
		this.friendsCount = friendsCount;
	}

	public long getBiFollowersCount() {
		return this.biFollowersCount;
	}

	public void setBiFollowersCount(long biFollowersCount) {
		this.biFollowersCount = biFollowersCount;
	}

	public long getStatusesCount() {
		return this.statusesCount;
	}

	public void setStatusesCount(long statusesCount) {
		this.statusesCount = statusesCount;
	}

	public Long getFavouritesCount() {
		return this.favouritesCount;
	}

	public void setFavouritesCount(Long favouritesCount) {
		this.favouritesCount = favouritesCount;
	}

	public Date getActiveAt() {
		return this.activeAt;
	}

	public void setActiveAt(Date activeAt) {
		this.activeAt = activeAt;
	}

	public Boolean getVerified() {
		return this.verified;
	}

	public void setVerified(Boolean verified) {
		this.verified = verified;
	}

	public Short getVerifiedType() {
		return this.verifiedType;
	}

	public void setVerifiedType(Short verifiedType) {
		this.verifiedType = verifiedType;
	}

	public String getVerifiedReason() {
		return this.verifiedReason;
	}

	public void setVerifiedReason(String verifiedReason) {
		this.verifiedReason = verifiedReason;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public Byte getBirthdayVisible() {
		return this.birthdayVisible;
	}

	public void setBirthdayVisible(Byte birthdayVisible) {
		this.birthdayVisible = birthdayVisible;
	}

	public Integer getCredentialsNum() {
		return this.credentialsNum;
	}

	public void setCredentialsNum(Integer credentialsNum) {
		this.credentialsNum = credentialsNum;
	}

	public Integer getCredentialsType() {
		return this.credentialsType;
	}

	public void setCredentialsType(Integer credentialsType) {
		this.credentialsType = credentialsType;
	}

	public String getMsn() {
		return this.msn;
	}

	public void setMsn(String msn) {
		this.msn = msn;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	public Date getRegTime() {
		return this.regTime;
	}

	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}

	public Date getRefreshTime() {
		return this.refreshTime;
	}

	public void setRefreshTime(Date refreshTime) {
		this.refreshTime = refreshTime;
	}

}
